/data/zhangx/anaconda3/envs/chineseocr-darknet/bin/python: can't open file 'manage.py': [Errno 2] No such file or directory
/data/zhangx/anaconda3/envs/chineseocr-darknet/bin/python: can't open file 'manage.py': [Errno 2] No such file or directory
/data/zhangx/anaconda3/envs/chineseocr-darknet/bin/python: can't open file 'manage.py': [Errno 2] No such file or directory
/data/zhangx/anaconda3/envs/chineseocr-darknet/bin/python: can't open file 'manage.py': [Errno 2] No such file or directory
